FUNCTION ZFM_GET_SFLIGHT_DATA_T16_NAMDV.
  DATA: LT_SFLIGHT TYPE ZTT_SFLIGHT_NAMDV.

  SELECT CONNID,
         FLDATE,
         PRICE,
         CURRENCY,
         SEATSMAX,
         SEATSOCC,
         SEATSMAX_B,
         SEATSOCC_B,
         SEATSMAX_F,
         SEATSOCC_F,
         ( SEATSMAX - SEATSOCC ) AS VAC_SEATS,
         ( SEATSMAX_B - SEATSOCC_B ) AS VAC_SEATS_B,
         ( SEATSMAX_F - SEATSOCC_F ) AS VAC_SEATS_F,
         SFLIGHT~CARRID,
         SCARR~CARRNAME
  FROM ZY052T AS SFLIGHT
  JOIN ZY050T AS SCARR
    ON SCARR~CARRID = SFLIGHT~CARRID
  WHERE SFLIGHT~CARRID = @IV_CARRID
    AND SFLIGHT~CONNID IN @IT_CONNID
  INTO CORRESPONDING FIELDS OF TABLE @LT_SFLIGHT.

  ET_SFLIGHT = LT_SFLIGHT.
ENDFUNCTION.